name: Newman Test Run
on:
  push:
    branches:
    - main
    - staging
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
      - run: npm install -g newman
      - run: newman run "https://api.getpostman.com/collections/26642903-d96183d6-7726-4c58-bd39-522ca3c6ffb0?apikey=${{ secrets.POSTMAN_API_KEY }}" --environment "https://api.getpostman.com/environments/26642903-9fee7d9a-725b-409a-8806-1359b9cf6837?apikey=${{ secrets.POSTMAN_API_KEY }}"

      - name: Publicar reporte HTML
        uses: actions/upload-artifact@v2
        with:
          name: newman-results
          path: ./newman/newman-results.html